### ISSUE TITLE
MVP #2: UserAuth

### ISSUE THREAD

**Issue by pvulakh** [pdfernandes/tikr#3]
Great work on this! A few changes to make:

### `Splash`
- [x] your navbar should have links to your linkedin and a dummy link for what will be your personal website. Add those in and style your navbar so that the links are not in the center
- [x] the spacing in the "Get Started" section looks kind of weird - add in margin/padding 
- [x] the disclaimer text in the footer should have the same font as the rest of your site
- [x] the footer itself is too long - remove the extra space at the very bottom

### `Login` 
- [x] add some padding to the error, it looks a bit crowded. There is also a typo, should be "provided" credentials

### `Signup`
- [x] the `First name` input is a bit to the right in comparison to inputs below it - align these
- [x] the error styling needs some work. If multiple inputs have errors, the error per input is shown only if that input is being clicked on. When you submit the form to generate errors, the first input that has an error is automatically clicked on for you. This will take some refactoring but will make your errors look cleaner. 
- [x] aside from that restructuring, make sure your error divs have a triangle pointing to the input that it corresponds to (you can do this by adding another div and rotating it 45 degrees to look like a triangle)
- [x] the error divs don't show the entire error message depending on the size of the window. This is error styling fix is of higher priority than the others

### Home when logged in
- [x] add an on hover effect for the `Log out` link in the navbar

**Comment by pdfernandes** [comment]
got it
